project:
  type: website

website:
  title: "ggsql"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - examples.qmd

format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true



