name: build-test.yaml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install tree sitter
        run: npm install -g tree-sitter-cli

      - name: Check disk space
        run: df -h

      - name: Regenerate parser
        working-directory: tree-sitter-ggsql
        run: tree-sitter generate

      - name: Run tree-sitter tests
        working-directory: tree-sitter-ggsql
        run: tree-sitter test

      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**Cargo.lock')}}

      - name: Build with cargo
        run: cargo build

      - name: Run Rust tests
        if: success()
        run: cargo test

      - name: Run Rust formatting check
        if: success()
        run: cargo fmt --all -- --check

  publish-website:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install tree sitter
        run: npm install -g tree-sitter-cli

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**Cargo.lock')}}

      - name: Regenerate parser
        working-directory: tree-sitter-ggsql
        run: tree-sitter generate

      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Jupyter
        run: python3 -m pip install jupyter jupyterlab

      - name: Build Jupyter kernel
        run: cargo build --release --package ggsql-jupyter

      - name: Install Jupyter kernel
        run: ./target/release/ggsql-jupyter --install

      - name: Render and Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: doc

  R-CMD-Check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**Cargo.lock')}}

      - name: Install tree sitter
        run: npm install -g tree-sitter-cli

      - name: Check disk space
        run: df -h

      - name: Regenerate parser
        working-directory: tree-sitter-ggsql
        run: tree-sitter generate

      - name: Setup CLI tools
        run: cargo install --path src

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          working-directory: ggsql-R

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ggsql-R
          extra-packages: any::rcmdcheck
          needs: check

      - name: Checking R package
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ggsql-R
